// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: sirsaugsage (https://sketchfab.com/sirsausage)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
// Title: Fantasy Game Inn
// */

// import { useGLTF } from "@react-three/drei";
// import { RigidBody } from "@react-three/rapier";

// export default function Map(props) {
//   const { nodes, materials } = useGLTF("./fantasy_game_inn.glb");

//   return (
//     <RigidBody type="fixed" colliders="trimesh" ccd>
//       <group {...props} dispose={null}>
//         <group rotation={[-Math.PI / 2, 0, 0]} scale={0.11}>
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.TheInn_bakeInn_0.geometry}
//           >
//             <meshStandardMaterial map={materials.bakeInn.map} />
//           </mesh>
//         </group>
//       </group>
//     </RigidBody>
//   );
// }

// useGLTF.preload("./fantasy_game_inn.glb");
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/second-scene.glb");
  return (
    <RigidBody type="fixed" colliders="trimesh" ccd>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Bg}
          scale={15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Terrain.geometry}
          material={materials.Ground}
          scale={4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Water}
          position={[2.9, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Road.geometry}
          material={materials.Road}
          scale={4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RoadLines.geometry}
          material={materials["Road Lines"]}
          position={[1.489, 1.256, 3.374]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock.geometry}
          material={materials.Rock}
          position={[-2.587, 1.146, -0.555]}
          rotation={[0, -1.552, 0]}
          scale={0.446}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock001.geometry}
          material={materials.Rock}
          position={[-2.809, 1.188, 2.51]}
          rotation={[2.739, 0.199, 0.096]}
          scale={0.524}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock002.geometry}
          material={materials.Rock}
          position={[3.008, 0.904, -0.269]}
          rotation={[-1.81, 1.158, 1.693]}
          scale={0.303}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock003.geometry}
          material={materials.Rock}
          position={[-1.802, 0.765, 1.373]}
          rotation={[-2.309, -1.115, 0.544]}
          scale={0.363}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock004.geometry}
          material={materials.Rock}
          position={[-0.247, 1.371, -2.265]}
          rotation={[0.085, 0.564, -0.164]}
          scale={0.373}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock005.geometry}
          material={materials.Rock}
          position={[-2.128, 1.509, -2.812]}
          rotation={[-2.38, 1.107, -1.013]}
          scale={0.414}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock006.geometry}
          material={materials.Rock}
          position={[-2.092, 1.449, -1.897]}
          rotation={[2.739, 0.199, 0.096]}
          scale={0.122}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock007.geometry}
          material={materials.Rock}
          position={[-2.128, 0.825, 2.084]}
          rotation={[-2.309, -1.115, 0.544]}
          scale={0.075}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock008.geometry}
          material={materials.Rock}
          position={[2.68, 1.06, 2.771]}
          rotation={[-2.309, -1.115, 0.544]}
          scale={0.158}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rock009.geometry}
          material={materials.Rock}
          position={[2.914, 1.024, -2.745]}
          rotation={[2.739, 0.199, 0.096]}
          scale={0.123}
        />
        <group
          position={[-1.243, 1.248, -0.369]}
          rotation={[-3.066, -0.267, -2.864]}
          scale={0.557}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tree}
          />
        </group>
        <group
          position={[-1.24, 1.243, 2.744]}
          rotation={[-0.113, 0.764, 0.159]}
          scale={[0.532, 0.519, 0.532]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tree}
          />
        </group>
        <group
          position={[-0.956, 1.417, -3.174]}
          rotation={[-2.976, 0.7, 3.041]}
          scale={0.466}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tree}
          />
        </group>
        <group
          position={[2.734, 1.261, -0.772]}
          rotation={[-0.251, -1.037, -0.346]}
          scale={0.461}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tree}
          />
        </group>
        <group
          position={[2.82, 1.359, 1.059]}
          rotation={[0.111, -1.153, 0.087]}
          scale={0.356}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Trunk}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tree}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/second-scene.glb");
